### ISSUE TITLE
Not applicable to folders in mapped network drivers

### ISSUE THREAD

**Issue by Naozheng** [kweatherman/Folcolor#15]
I found it not applicable to folders in mapped network drivers... Was it coded this way or maybe I missed any configuration...

**Comment by kweatherman** [comment]
Can you be more descriptive? 
Clearly what is the problem, how can I reproduce the problem?

**Comment by Naozheng** [comment]
![image](https://github.com/kweatherman/Folcolor/assets/102581434/9fa4f3d2-05cf-4712-9d79-18fae3294205)
When I tried to apply to the folders in mapped network driver (which you can see the snap attached), the color of the folder was not changed. Refreshing was no help. This network driver was mapped from my NAS via Samba. I just tried with another networked driver mapped from other PC, not working either.

**Comment by kweatherman** [comment]
I see. Can you check to see if the remote folder has a "desktop.ini" in it?
In Windows explorer you have to go into the "Folder Options" and under "View" and uncheck the "Hide protected operating system files (Recommended)".

That would be the first problem. Not sure if Windows will allow setting (creating if doesn't exist) these "desktop.ini" remotely.
Might not help either that your NAS server is probably Linux using Ext4 not NTFS.
But I'm not so sure this is the problem. It's really getting into OS factors though.

Would mind checking to see if Folcolor is able to write (through the Windows API) a "desktop.ini" in the destination folder?
If it doesn't try setting the color for a local folder and then copy the "desktop.ini" from that folder over to the remote folder.
Although still probably the file would be need to have the "system" attribute. 
If it was local you can use "attrib" to set the "system" attribute to a file. And since the remote OS might be Ext4, this still might not work. 

For Linux you could use "chattr" to change permissions (Microsoft uses the name "attributes") and Linux doesn't even have a "system" permission.

**Comment by Naozheng** [comment]
I copied the "desktop.ini" file to the folder in remote driver from my local folder. I set "system" attribute to the remote folder, then the folder turned into the same color as the original local folder. However, I have to manually set attribute to specified remote folder in cmd  and modify the number code in the "desktop.ini" file, and press "refresh" everytime.

It basically worked after all. Thanks a lot.

**Comment by kweatherman** [comment]
Okay, good to know it will at least work this way.
Already it takes administrator privilege's to even set these "desktop.ini" files, etc.
Must be some trick, like some missing flag or something to allow it to happen over a network.
I'll look into it to see if there is a solution to avoid having to do those manual steps.

**Comment by b4nn** [comment]
hi @kweatherman! Wondering if you have any update on the issue with mapped folders? I saw the manual solution above but it's too time consuming for to my needs since I change status (color) of folders too often.
