### ISSUE TITLE
[suggestion] Folcolor doesn't show folder color on another PC

### ISSUE THREAD

**Issue by mitsuki0316** [kweatherman/Folcolor#2]
Sorry for my bad English... (it's a suggestion but the title looks like a bug)

folder color becomes a normal color when I open the folder on another pc.
so I think it's happy if there are settings for it :D (Disable/Enable, can work on another pc or not)

I mean, there's a way to do that.
it can be made with 1 folder that puts the .ico file and editing desktop.ini like this:
```
[.ShellClassInfo]
IconResource=.Foldercolor\abc.ico,0
```

or maybe 1 .ico file and editing desktop.ini like this:
```
[.ShellClassInfo]
IconFile=abc.ico
IconIndex=0
```

but sad fact is I can't English and coding :(
so I suggested this.

and sorry again for this bad English, thanks for reading.

**Comment by kweatherman** [comment]
No problem.  
Interesting. So when you open the folder on another computer over a network you have this problem right?  
I would think if you just install Folcolor on the other machines on your network this would fix it.  

Focolor uses an absolute path ("C:\Program Files (x86)\Folcolor\Folcolor.exe") to the executable that acts as both a icon DB and as  utility to set up a "desktop.ini" file.  
Although a problem here is that if one computer is using Windows 7 or 8, then the other ising using Windows 10. The icons will be colored still but it won't look right since the base folder images are different between the OSes.  
 
If I understand you right, you mean what if the color icon is put in the same folder where the "desktop.ini" goes right?
This way the icon will always be available even without Folcolor being installed.  
With at least [Folder Marker](https://foldermarker.com/en/) you can do this by using the "Make customized folder distributable" checkbox. Also the Windows 7/8 vrs 10 versions folder sets difference thing will still be a problem using their tool.  
It would take some sort of on the fly Windows internals thing to handle problem properly.  

I don't intend adding such a feature to Folcolor mainly since:  
1) I like to leave the "Hide protected operating system files" explorer option unchecked.  
    The icon file there means more clutter in file folders to look at.  
2) My design criteria was to make Folcolor small and minimalist.  

But you are free to fork Folcolor and make a version that does what you want.

**Comment by mitsuki0316** [comment]
Ohh okay, now I understand your opinion :O
you can close this, thanks for replying :D
