### ISSUE TITLE
Asks "Do you want to allow this app from an unknown publisher to make changes to your computer?" every single time

### ISSUE THREAD

**Issue by gvivster** [kweatherman/Folcolor#20]
Windows 10 prompts me with this question every single time. If I highlight multiple folders and change their color all at once, it will ask me once for each folder, one after the other.

If that were solved, this app would be perfect!

**Comment by kweatherman** [comment]
Thanks. That's the User Account Control (UAC) dialog box that comes up because Folcolor needs to run as administrator.
Maybe there is a way to not have the UAC dialog box not come up, like signing the executable a special Microsoft way.
Other possibilities are using some sort of hacks/exploits which I don't want to use.

What you can do, at least temporary, if you have a lot of folders you want to set. Search the Windows/Cortana box for "UAC" and run the settings. If you drop it all the way down you won't get the notification anymore. But this is not so good long term because it's good to know when programs want to run as admin. You should comeback later and set it to at least the last of the four levels so you'll get notified again.
