### ISSUE TITLE
[Feature request] I'd like to create my own custom color, and skip the irritating UAC

### ISSUE THREAD

**Issue by Dhyfer1** [kweatherman/Folcolor#8]
Hi.

I like Folcolor. Before knowing your program I had tried other alternatives (Rainbow Folders, CustomFolder, FolderPainter, Folder Changer, Folder Marker, FolderIco, Folder Colorizer etc...). Some of these programs have an option to change the folder color by adding a hex or RGB value in a color editor.

Folcolor looks a bit like [Folder Colorizer 2](https://softorino.com/foldercolorizer2/) software. Were you inspired by it to create FolColor? I would say that Folcolor is the best free alternative to Folder Colorizer 2 (FC2 prides itself on being able to change the color of a folder in less than 1 second).

I would like Folcolor to have an option to add more colors, the pre-selected colors are ok, but sometimes they are not enough, for this reason it would be nice if the user could create a custom color using a built-in color wheel, as you can see in the Folder Colorizer 2 image.

![image_1](https://user-images.githubusercontent.com/50301201/192165150-1f1cf4ed-2955-4cee-9b41-c837adfdd247.png)

I would also like Folcolor to stop showing the UAC every time I want to change the color of a folder, it's a bit annoying.

That's all, and I would like to know what you think about it.

**Comment by kweatherman** [comment]
Like I say on http://www.folcolor.com/, I tried several. 
I would have probably gone with one of the commercial ones if I found one that didn't have adds, annoying DRM feature, wasn't a security risk, etc.

I just wanted to make about as minimal as it gets with a few colors so that's what I made.
If anything maybe I might add more colors (same type of menu but in a tree), but I'm not going to be adding and kind of editor or configuration option any time soon.

UAC dialog: I actually spent a few days trying the windows task scheduler elevation trick (like what CCleaner does). It works but the problem is you can't pass parameters to the task apparently. Would probably have to have the executable shell it's self, and spent more time than I wanted trying to get the simple Microsoft C++ COM example to run a task. Since most of the other ones  use a shell extension that lives inside of explorer.exe it's already elevated, thus won't get a UAC box. I suppose I could do some other trick, maybe hijacking an elevated process handle, but then already stupid virus scanners see my utility as malware even without that.

If that one is only $2.92 now that's hard to beat unless you have a lot of machines, etc.

Another free one where it would be easy to change the icons is:
https://www.sordum.org/10124/folder-painter-v1-3/
